name: Nx Affected Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin main
      - name: npm install
        run: npm install
      - name: Run Affected Deploy
        shell: bash
        run: npm run affected:deploy -- --base=remotes/origin/main
